# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.

GTEST = ../googletest/googletest
GTEST_LIB = $(GTEST)/lib

SRC = ./src
INCLUDE = ./include
TEST = ./test
LIB = ./lib

BIN = ./build/bin
OBJ = ./build/obj

# Set Google Test's header directory as a system directory, such that
# the compiler doesn't generate warnings in Google Test headers.
CPPFLAGS += -isystem $(GTEST)/include
CXXFLAGS += -g -Wall -Wextra -std=c++11

GTEST_STATIC = $(GTEST_LIB)/libgtest.a

TESTS = $(BIN)/testNlpSolver

GTEST_HEADERS = $(GTEST)/include/gtest/*.h \
                $(GTEST)/include/gtest/internal/*.h

all : $(GTEST_LIBS) $(TESTS)
gtest: $(GTEST_LIBS)
clean:
	rm -f $(TESTS) $(OBJ)/*.o	
clean-all :
	rm -f $(GTEST_LIBS) $(TESTS) $(OBJ)/*.o

# Builds gtest.a and gtest_main.a.
GTEST_SRCS_ = $(GTEST)/src/*.cc $(GTEST)/src/*.h $(GTEST_HEADERS)
$(OBJ)/gtest-all.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST) $(CXXFLAGS) -c \
            $(GTEST)/src/gtest-all.cc -o $@
$(OBJ)/gtest_main.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST) $(CXXFLAGS) -c \
            $(GTEST)/src/gtest_main.cc -o $@
$(GTEST_LIB)/libgtest.a : $(OBJ)/gtest-all.o
	$(AR) $(ARFLAGS) $@ $^
$(GTEST_LIB)/libgtest_main.a : $(OBJ)/gtest-all.o $(OBJ)/gtest_main.o
	$(AR) $(ARFLAGS) $@ $^

# builds OclSolver
$(OBJ)/NlpSolver.o : $(SRC)/NlpSolver.cc $(INCLUDE)/NlpSolver.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -I$(SRC) -I$(INCLUDE) -c $< -o $@

$(OBJ)/testNlpSolver.o : $(TEST)/testNlpSolver.cc $(INCLUDE)/NlpSolver.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -I$(SRC) -I$(INCLUDE) -c $< -o $@

$(BIN)/testNlpSolver : $(OBJ)/NlpSolver.o $(OBJ)/testNlpSolver.o $(GTEST_STATIC)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -L$(GTEST_LIB) -lgtest_main -lpthread $^ -o $@


